import { chmodSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { launcherName } from "./launchers"

/**
 * A launcher the HOST writes for a `runtime: node` (or `wasm`) tool bit that ships none.
 *
 * Why this exists. The editor's own Node is `process.execPath`, and on Windows that binary is
 * `Code.exe`. It only behaves as Node when `ELECTRON_RUN_AS_NODE=1` is in the environment — which the
 * two built-in doors set (`TriggerNordicActionHandler`, `TriggerCveScanHandler`) and a shell command
 * cannot: the advertisement hands the agent a command line, not an environment. So the agent ran
 * `Code.exe …\seed.mjs`, which OPENS THE FILE IN THE EDITOR. Nothing executed, and a cache-internal
 * file was put in front of the developer (Omar, 0.4.0 test log, 2026-09-09).
 *
 * The fix is the same one Python tools already have: a launcher file named after the tool, so the
 * advertised command is `…/lew840x-gateway-seeds.bat --into .` — a path whose basename is the name the
 * knowledge bits use, and whose contents carry the environment. The agent never constructs an
 * interpreter call, and the demonstration lines in the corpus (`lew840x-gateway-seeds --into …`)
 * resolve to something real.
 *
 * Written idempotently — only when absent or when the content would change — so a resolve is cheap
 * and a bundle whose cache directory is rebuilt gets its launcher back on the next resolve.
 */

export interface GeneratedLauncherArgs {
	/** The tool's user-facing name — the launcher's filename. */
	toolName: string
	/** Absolute path to the tool's entry file. */
	entryPath: string
	/** Directory the launcher is written into. Created if missing. */
	dir: string
	platform?: NodeJS.Platform
	/** The editor's Node. Defaults to `process.execPath`. */
	nodePath?: string
}

/** The launcher text for a platform. Pure, so a test can assert the exact contract. */
export function generatedLauncherText(args: { entryPath: string; nodePath: string; platform: NodeJS.Platform }): string {
	const { entryPath, nodePath, platform } = args
	if (platform === "win32") {
		// setlocal keeps ELECTRON_RUN_AS_NODE from leaking into the developer's shell after the tool exits.
		return [
			"@echo off",
			"REM Generated by Adsum — runs a node tool bit under the editor's own Node.",
			"REM On Windows that binary is Code.exe; without this variable it opens files instead of running them.",
			"setlocal",
			"set ELECTRON_RUN_AS_NODE=1",
			`"${nodePath}" "${entryPath}" %*`,
			"exit /b %errorlevel%",
			"",
		].join("\r\n")
	}
	return [
		"#!/bin/sh",
		"# Generated by Adsum — runs a node tool bit under the editor's own Node.",
		`exec env ELECTRON_RUN_AS_NODE=1 "${nodePath}" "${entryPath}" "$@"`,
		"",
	].join("\n")
}

/**
 * Ensure the launcher exists and is current. Returns its absolute path, or null if it could not be
 * written — a read-only location, a full disk. Never throws: a tool that cannot get a launcher is
 * advertised without one rather than breaking prompt assembly, and `buildResolvedTool` then falls back
 * to the bare interpreter form, which is the pre-existing behaviour.
 */
export function ensureGeneratedLauncher(args: GeneratedLauncherArgs): string | null {
	const platform = args.platform ?? process.platform
	const nodePath = args.nodePath ?? process.execPath
	const file = path.join(args.dir, launcherName(args.toolName, platform))
	const text = generatedLauncherText({ entryPath: args.entryPath, nodePath, platform })
	try {
		if (existsSync(file) && readFileSync(file, "utf8") === text) {
			return file
		}
		mkdirSync(args.dir, { recursive: true })
		writeFileSync(file, text, { mode: 0o755 })
		if (platform !== "win32") {
			chmodSync(file, 0o755) // writeFileSync's mode is masked by umask; the exec bit must be certain
		}
		return file
	} catch {
		return null
	}
}
