// Aggregate runner — imports every CVE-substrate node:test so `npm run test:cve` runs them in one process.
// (Each module file registers its tests at import; node:test runs them all.)
import "./sbomNormalize.node-test"
import "./osvMatch.node-test"
import "./applicability.node-test"
import "./scanLoop.node-test"
import "./parity.node-test"
import "./evidenceReport.node-test"
import "./osvFetcher.node-test"
import "./buildEvidence.node-test"
import "./advisoryHints.node-test"
import "./componentPurlMap.node-test"
import "./cveScanHost.node-test"
import "./cveScanIntegration.node-test"
import "./osvEnrich.node-test"
import "./westVersions.node-test"
import "./vexEmit.node-test"
import "./reportIntegrity.node-test"
import "./nvdMatch.node-test"
import "./moduleSecurityRefs.node-test"
import "./euvdFetcher.node-test"
import "./fixCommitResolver.node-test"
